// Code generated by gohandlers . DO NOT EDIT.

package client

import (
	"github.com/ufukty/gohandlers-petstore/handlers/pets"
	"net/http"
)

type Interface interface {
	CreatePet(*pets.CreatePetRequest) (*http.Response, error)
	DeletePet(*pets.DeletePetRequest) (*http.Response, error)
	GetPet(*pets.GetPetRequest) (*http.Response, error)
	ListPets(*pets.ListPetsRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CreatePet(*pets.CreatePetRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) DeletePet(*pets.DeletePetRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) GetPet(*pets.GetPetRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) ListPets(*pets.ListPetsRequest) (*http.Response, error) {
	return nil, nil
}
