// Code generated by gohandlers v0.34.0. DO NOT EDIT.

package client

import (
	"github.com/ufukty/gohandlers-petstore/handlers/pets"
	"net/http"
)

type Interface interface {
	CreatePet(*pets.CreatePetRequest) (*pets.CreatePetResponse, error)
	DeletePet(*pets.DeletePetRequest) (*http.Response, error)
	GetPet(*pets.GetPetRequest) (*pets.GetPetResponse, error)
	ListPets(*pets.ListPetsRequest) (*pets.ListPetsResponse, error)
}

type Mock struct {
}

func (m *Mock) CreatePet(*pets.CreatePetRequest) (*pets.CreatePetResponse, error) {
	return nil, nil
}

func (m *Mock) DeletePet(*pets.DeletePetRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) GetPet(*pets.GetPetRequest) (*pets.GetPetResponse, error) {
	return nil, nil
}

func (m *Mock) ListPets(*pets.ListPetsRequest) (*pets.ListPetsResponse, error) {
	return nil, nil
}
