// Code generated by gohandlers v0.34.0. DO NOT EDIT.

package client

import (
	"github.com/ufukty/gohandlers-petstore/handlers/pets"
	"net/http"
)

type Interface interface {
	Create(*pets.CreateRequest) (*pets.CreateResponse, error)
	Delete(*pets.DeleteRequest) (*http.Response, error)
	Get(*pets.GetRequest) (*pets.GetResponse, error)
	List(*pets.ListRequest) (*pets.ListResponse, error)
}

type Mock struct {
}

func (m *Mock) Create(*pets.CreateRequest) (*pets.CreateResponse, error) {
	return nil, nil
}

func (m *Mock) Delete(*pets.DeleteRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) Get(*pets.GetRequest) (*pets.GetResponse, error) {
	return nil, nil
}

func (m *Mock) List(*pets.ListRequest) (*pets.ListResponse, error) {
	return nil, nil
}
