// Code generated by gohandlers . DO NOT EDIT.

package pets

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

func join(segments ...string) string {
	url := ""
	for i, segment := range segments {
		if i != 0 && !strings.HasPrefix(segment, "/") {
			url += "/"
		}
		url += segment
	}
	return url
}

func (bq CreatePetRequest) Build(host string) (*http.Request, error) {
	uri := "/create-pet"
	body := bytes.NewBuffer([]byte{})
	if err := json.NewEncoder(body).Encode(bq); err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	r, err := http.NewRequest("POST", join(host, uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}

func (bq *CreatePetRequest) Parse(rq *http.Request) error {
	if !strings.HasPrefix(rq.Header.Get("Content-Type"), "application/json") {
		return fmt.Errorf("invalid content type for request: %s", rq.Header.Get("Content-Type"))
	}
	if err := json.NewDecoder(rq.Body).Decode(bq); err != nil {
		return fmt.Errorf("decoding body: %w", err)
	}
	return nil
}

func (bs CreatePetResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(bs); err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *CreatePetResponse) Parse(rs *http.Response) error {
	if !strings.HasPrefix(rs.Header.Get("Content-Type"), "application/json") {
		return fmt.Errorf("invalid content type for request: %s", rs.Header.Get("Content-Type"))
	}
	if err := json.NewDecoder(rs.Body).Decode(bs); err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}

func (bq DeletePetRequest) Build(host string) (*http.Request, error) {
	uri := "/pets/{id}"
	encoded, err := bq.ID.ToRoute()
	if err != nil {
		return nil, fmt.Errorf("DeletePetRequest.ID.ToRoute: %w", err)
	}
	uri = strings.Replace(uri, "{id}", encoded, 1)
	r, err := http.NewRequest("DELETE", join(host, uri), nil)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	return r, nil
}

func (bq *DeletePetRequest) Parse(rq *http.Request) error {
	if err := bq.ID.FromRoute(rq.PathValue("id")); err != nil {
		return fmt.Errorf("DeletePetRequest.ID.FromRoute: %w", err)
	}
	return nil
}

func (bq GetPetRequest) Build(host string) (*http.Request, error) {
	uri := "/pets/{id}"
	encoded, err := bq.ID.ToRoute()
	if err != nil {
		return nil, fmt.Errorf("GetPetRequest.ID.ToRoute: %w", err)
	}
	uri = strings.Replace(uri, "{id}", encoded, 1)
	r, err := http.NewRequest("GET", join(host, uri), nil)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	return r, nil
}

func (bq *GetPetRequest) Parse(rq *http.Request) error {
	if err := bq.ID.FromRoute(rq.PathValue("id")); err != nil {
		return fmt.Errorf("GetPetRequest.ID.FromRoute: %w", err)
	}
	return nil
}

func (bs GetPetResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(bs); err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *GetPetResponse) Parse(rs *http.Response) error {
	if !strings.HasPrefix(rs.Header.Get("Content-Type"), "application/json") {
		return fmt.Errorf("invalid content type for request: %s", rs.Header.Get("Content-Type"))
	}
	if err := json.NewDecoder(rs.Body).Decode(bs); err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}

func (bq ListPetsRequest) Build(host string) (*http.Request, error) {
	uri := "/pets"
	q := []string{}
	encoded, ok, err := bq.Limit.ToQuery()
	if err != nil {
		return nil, fmt.Errorf("ListPetsRequest.Limit.ToQuery: %w", err)
	}
	if ok {
		q = append(q, fmt.Sprintf("limit=%s", encoded))
	}
	if len(q) > 0 {
		uri = fmt.Sprintf("%s?%s", uri, strings.Join(q, "&"))
	}
	r, err := http.NewRequest("GET", join(host, uri), nil)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	return r, nil
}

func (bq *ListPetsRequest) Parse(rq *http.Request) error {
	q := rq.URL.Query()
	if q.Has("limit") {
		err := bq.Limit.FromQuery(q.Get("limit"))
		if err != nil {
			return fmt.Errorf("ListPetsRequest.Limit.FromQuery: %w", err)
		}
	}
	return nil
}

func (bs ListPetsResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(bs); err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *ListPetsResponse) Parse(rs *http.Response) error {
	if !strings.HasPrefix(rs.Header.Get("Content-Type"), "application/json") {
		return fmt.Errorf("invalid content type for request: %s", rs.Header.Get("Content-Type"))
	}
	if err := json.NewDecoder(rs.Body).Decode(bs); err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}
