// Code generated by gohandlers v0.26.2. DO NOT EDIT.

package pets

import "net/http"

type HandlerInfo struct {
	Method string
	Path   string
	Ref    http.HandlerFunc
}

func (pe *Pets) ListHandlers() map[string]HandlerInfo {
	return map[string]HandlerInfo{
		"CreatePet": {Method: "POST", Path: "/create-pet", Ref: pe.CreatePet},
		"DeletePet": {Method: "DELETE", Path: "/pets/{id}", Ref: pe.DeletePet},
		"GetPet":    {Method: "GET", Path: "/pets/{id}", Ref: pe.GetPet},
		"ListPets":  {Method: "GET", Path: "/pets", Ref: pe.ListPets},
	}
}
